project_name: conk

builds:
  -
    main: ./cmd/conk/main.go
    ldflags:
    - "-X github.com/moznion/conk/internal.Revision={{ .FullCommit }}"
    - "-X github.com/moznion/conk/internal.Version={{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: desc

